#!/usr/bin/env bash
set -euo pipefail

# Build Overture in Release configuration and install to /Applications.
# Usage: ./build-install.sh [--launch]
#
# Overture's Xcode project is generated by xcodegen from project.yml, so we
# regenerate it first (when xcodegen is available) for a truly fresh build.

cd "$(dirname "$0")"

# shellcheck source=scripts/lib/install-dedupe.sh
source "$(pwd)/scripts/lib/install-dedupe.sh"
# shellcheck source=scripts/lib/await-registered.sh
source "$(pwd)/scripts/lib/await-registered.sh"
# shellcheck source=scripts/lib/launch-surface.sh
source "$(pwd)/scripts/lib/launch-surface.sh"
# shellcheck source=scripts/lib/stable-signing.sh
source "$(pwd)/scripts/lib/stable-signing.sh"

PROJECT="Overture.xcodeproj"
SCHEME="Overture"
CONFIG="Release"
APP_NAME="Overture.app"
DEST="/Applications/${APP_NAME}"
BUILD_DIR="$(pwd)/build"

if command -v xcodegen >/dev/null; then
  echo "==> Regenerating ${PROJECT} (xcodegen)"
  xcodegen generate >/dev/null
fi

echo "==> Building ${SCHEME} (${CONFIG})"
xcodebuild \
  -project "${PROJECT}" \
  -scheme "${SCHEME}" \
  -configuration "${CONFIG}" \
  -derivedDataPath "${BUILD_DIR}" \
  -destination 'platform=macOS' \
  CODE_SIGN_IDENTITY="-" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  build \
  | (command -v xcbeautify >/dev/null && xcbeautify || cat)

BUILT_APP="${BUILD_DIR}/Build/Products/${CONFIG}/${APP_NAME}"
if [[ ! -d "${BUILT_APP}" ]]; then
  echo "Error: build succeeded but ${BUILT_APP} not found" >&2
  exit 1
fi

# Login agent that keeps Overture resident across logins (#267 / Phase 3 of #237).
AGENT_LABEL="com.danwright.overture"
AGENT_SRC="$(pwd)/launchd/${AGENT_LABEL}.plist"
AGENT_DEST="${HOME}/Library/LaunchAgents/${AGENT_LABEL}.plist"
GUI_DOMAIN="gui/$(id -u)"

echo "==> Installing to ${DEST}"
# Unload any running login agent FIRST so it can't respawn the old binary while we swap the bundle.
# Best-effort: on a first-ever install there is no agent to boot out yet.
launchctl bootout "${GUI_DOMAIN}/${AGENT_LABEL}" 2>/dev/null || true
if [[ -d "${DEST}" ]]; then
  # A copy launched by hand (not by the agent) won't be stopped by bootout; quit it so the
  # replace doesn't fail.
  if pgrep -xq "Overture"; then
    echo "    Quitting running Overture..."
    osascript -e 'tell application "Overture" to quit' || true
    sleep 1
  fi
  rm -rf "${DEST}"
fi
cp -R "${BUILT_APP}" "${DEST}"

# Strip quarantine so Gatekeeper doesn't nag on first launch.
xattr -dr com.apple.quarantine "${DEST}" 2>/dev/null || true

# Sign with the stable local identity so the bundle presents the SAME code signature on every
# reinstall, which is what lets macOS keep TCC grants (calendar, Gmail/automation, reminders) instead
# of dropping them (#1425). An ad-hoc signature does NOT do this: its cdhash is a hash of the binary
# and changes every rebuild, so macOS treats each reinstall as a different app. overture_stable_sign
# fails loud if the identity is missing (run mac/scripts/setup-signing-identity.sh once) rather than
# silently falling back to ad-hoc.
overture_stable_sign "${DEST}"

# Drop the stray build copy and make /Applications the canonical overture:// handler, so the
# `open overture://show` surface below can only resolve to the installed bundle. Without this a
# second Release copy in the build products shadowed it and launched a duplicate the store lock
# then refused (the "Overture's data is unavailable" clash, 2026-07-18).
overture_dedupe_installed_bundle "${BUILT_APP}" "${DEST}"

# #1808: record what was just installed, so the app can tell Dan when the copy he is looking at has
# fallen behind the code. Nothing else knows this: the app cannot run git, and it cannot know which
# checkout produced the bundle in /Applications. `repoPath` is what makes the panel's Update button
# possible at all, since that is where the button has to run this script from.
#
# Written AFTER the install succeeds, never before: a record of an install that did not happen would
# have the app comparing against a bundle that is not there (L12, report what verifiably happened).
# "After the install succeeds" means after the bundle verifiably landed in /Applications and was signed,
# which is done by here, NOT after the app has been started.
#
# #2065: and BEFORE the login agent below, which launches Overture. These two lines used to sit at the
# end of the script, after the bootstrap, so the app's launch-time read raced the write and lost: on
# 2026-08-04 the app started at 10:00:09, this file was written at 10:00:09, and Dan was still being
# told at 12:09 that his copy "did not come from the installer" with the Update button withheld. The
# ordering guarantees the first launch after EVERY install lost that race, which made the panel's most
# common appearance its wrong one. Keep these writes above the bootstrap.
OVERTURE_REPO_ROOT="$(cd "$(pwd)/.." && pwd)"
OVERTURE_DATA_DIR="${HOME}/Library/Application Support/Overture"
INSTALLED_COMMIT="$(git -C "${OVERTURE_REPO_ROOT}" rev-parse HEAD)"
INSTALLED_COMMIT_DATE="$(git -C "${OVERTURE_REPO_ROOT}" log -1 --format=%cI HEAD)"
mkdir -p "${OVERTURE_DATA_DIR}"
INSTALLED_TMP="$(mktemp "${OVERTURE_DATA_DIR}/.installed-build.XXXXXX")"
printf '{"version":1,"commit":"%s","commitDate":"%s","repoPath":"%s"}\n' \
  "${INSTALLED_COMMIT}" "${INSTALLED_COMMIT_DATE}" "${OVERTURE_REPO_ROOT}" > "${INSTALLED_TMP}"
mv -f "${INSTALLED_TMP}" "${OVERTURE_DATA_DIR}/installed-build.json"
echo "==> Recorded installed build: ${INSTALLED_COMMIT:0:7}"

# And what has shipped, through the one shared writer, so a freshly installed Mac never sits in the
# "nothing has recorded a merge" state with a panel it has no way to clear.
"${OVERTURE_REPO_ROOT}/scripts/record-shipped-commit.sh" || true

# Install/refresh the login agent and load it into the user's GUI (Aqua) session. The GUI session
# is what the menu-bar NSStatusItem requires (a system domain would have no menu bar). RunAtLoad then
# starts Overture resident immediately and again at every login.
echo "==> Installing login agent: ${AGENT_DEST}"
mkdir -p "${HOME}/Library/LaunchAgents"
# Owner-only log directory for the agent's stdout/stderr (#279). launchd opens StandardOutPath at
# spawn before any app code runs, so the directory must exist now; it lives under the user's own
# Library/Logs (private, survives reboots) instead of world-readable, reboot-cleared /tmp.
AGENT_LOG_DIR="${HOME}/Library/Logs/Overture"
mkdir -p "${AGENT_LOG_DIR}"
chmod 700 "${AGENT_LOG_DIR}"
# launchd does NOT expand ~, so bake the absolute log path into the installed plist copy.
sed "s|__OVERTURE_LOG_DIR__|${AGENT_LOG_DIR}|g" "${AGENT_SRC}" > "${AGENT_DEST}"
launchctl bootstrap "${GUI_DOMAIN}" "${AGENT_DEST}" \
  || echo "    (agent bootstrap reported an error; inspect with: launchctl print ${GUI_DOMAIN}/${AGENT_LABEL})"

echo "==> Installed: ${DEST} (resident via ${AGENT_LABEL})"

if [[ "${1:-}" == "--launch" ]]; then
  # The login agent already started Overture resident. Do NOT `open` the bundle: LaunchServices may
  # not associate the agent-spawned process, so `open` launches a SECOND copy that the store lock
  # then refuses (the #282 degraded-window clash). Instead surface the running copy via its URL
  # scheme, which routes to the already-running instance.
  #
  # #1160: but only AFTER the agent-started resident copy has registered with LaunchServices. Opening
  # the URL immediately after bootstrap raced that registration, so LaunchServices launched a SECOND
  # copy instead of routing to the first (LSMultipleInstancesProhibited only routes to an
  # already-registered instance). Wait for registration first; best-effort, and the in-app duplicate
  # guard (StoreLaunchOutcome) terminates any duplicate that still slips through.
  echo "==> Surfacing the resident Overture window"
  overture_await_bundle_registered "com.danwright.overture" \
    || echo "    (resident copy didn't confirm registration in time; surfacing anyway)"
  # #1120: pin the URL to the installed bundle by path (open -a "${DEST}"), never a bare
  # `open overture://show`, so LaunchServices cannot route the scheme to a stray Release copy and spawn a
  # duplicate. Args come one-per-line from the tested helper, read into an array so a spaced path is safe.
  OPEN_ARGS=()
  while IFS= read -r _arg; do OPEN_ARGS+=("${_arg}"); done < <(overture_launch_open_args "${DEST}")
  open "${OPEN_ARGS[@]}" 2>/dev/null || true
fi
