#!/usr/bin/env bash
set -euo pipefail

# Build Overture in Release configuration and install to /Applications.
# Usage: ./build-install.sh [--launch]
#
# Overture's Xcode project is generated by xcodegen from project.yml, so we
# regenerate it first (when xcodegen is available) for a truly fresh build.

cd "$(dirname "$0")"

PROJECT="Overture.xcodeproj"
SCHEME="Overture"
CONFIG="Release"
APP_NAME="Overture.app"
DEST="/Applications/${APP_NAME}"
BUILD_DIR="$(pwd)/build"

if command -v xcodegen >/dev/null; then
  echo "==> Regenerating ${PROJECT} (xcodegen)"
  xcodegen generate >/dev/null
fi

echo "==> Building ${SCHEME} (${CONFIG})"
xcodebuild \
  -project "${PROJECT}" \
  -scheme "${SCHEME}" \
  -configuration "${CONFIG}" \
  -derivedDataPath "${BUILD_DIR}" \
  -destination 'platform=macOS' \
  CODE_SIGN_IDENTITY="-" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  build \
  | (command -v xcbeautify >/dev/null && xcbeautify || cat)

BUILT_APP="${BUILD_DIR}/Build/Products/${CONFIG}/${APP_NAME}"
if [[ ! -d "${BUILT_APP}" ]]; then
  echo "Error: build succeeded but ${BUILT_APP} not found" >&2
  exit 1
fi

echo "==> Installing to ${DEST}"
if [[ -d "${DEST}" ]]; then
  # If the app is running, quit it first so the replace doesn't fail.
  if pgrep -xq "Overture"; then
    echo "    Quitting running Overture..."
    osascript -e 'tell application "Overture" to quit' || true
    sleep 1
  fi
  rm -rf "${DEST}"
fi
cp -R "${BUILT_APP}" "${DEST}"

# Strip quarantine so Gatekeeper doesn't nag on first launch.
xattr -dr com.apple.quarantine "${DEST}" 2>/dev/null || true

# Ad-hoc re-sign so the bundle identity is stable across rebuilds
# (helps TCC/Full Disk Access grants persist).
codesign --force --deep --sign - "${DEST}" >/dev/null 2>&1 || true

echo "==> Installed: ${DEST}"

if [[ "${1:-}" == "--launch" ]]; then
  echo "==> Launching"
  open "${DEST}"
fi
