#!/usr/bin/env bash
set -euo pipefail

# Build Overture in Release configuration and install to /Applications.
# Usage: ./build-install.sh [--launch]
#
# Overture's Xcode project is generated by xcodegen from project.yml, so we
# regenerate it first (when xcodegen is available) for a truly fresh build.

cd "$(dirname "$0")"

PROJECT="Overture.xcodeproj"
SCHEME="Overture"
CONFIG="Release"
APP_NAME="Overture.app"
DEST="/Applications/${APP_NAME}"
BUILD_DIR="$(pwd)/build"

if command -v xcodegen >/dev/null; then
  echo "==> Regenerating ${PROJECT} (xcodegen)"
  xcodegen generate >/dev/null
fi

echo "==> Building ${SCHEME} (${CONFIG})"
xcodebuild \
  -project "${PROJECT}" \
  -scheme "${SCHEME}" \
  -configuration "${CONFIG}" \
  -derivedDataPath "${BUILD_DIR}" \
  -destination 'platform=macOS' \
  CODE_SIGN_IDENTITY="-" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  build \
  | (command -v xcbeautify >/dev/null && xcbeautify || cat)

BUILT_APP="${BUILD_DIR}/Build/Products/${CONFIG}/${APP_NAME}"
if [[ ! -d "${BUILT_APP}" ]]; then
  echo "Error: build succeeded but ${BUILT_APP} not found" >&2
  exit 1
fi

# Login agent that keeps Overture resident across logins (#267 / Phase 3 of #237).
AGENT_LABEL="com.danwright.overture"
AGENT_SRC="$(pwd)/launchd/${AGENT_LABEL}.plist"
AGENT_DEST="${HOME}/Library/LaunchAgents/${AGENT_LABEL}.plist"
GUI_DOMAIN="gui/$(id -u)"

echo "==> Installing to ${DEST}"
# Unload any running login agent FIRST so it can't respawn the old binary while we swap the bundle.
# Best-effort: on a first-ever install there is no agent to boot out yet.
launchctl bootout "${GUI_DOMAIN}/${AGENT_LABEL}" 2>/dev/null || true
if [[ -d "${DEST}" ]]; then
  # A copy launched by hand (not by the agent) won't be stopped by bootout; quit it so the
  # replace doesn't fail.
  if pgrep -xq "Overture"; then
    echo "    Quitting running Overture..."
    osascript -e 'tell application "Overture" to quit' || true
    sleep 1
  fi
  rm -rf "${DEST}"
fi
cp -R "${BUILT_APP}" "${DEST}"

# Strip quarantine so Gatekeeper doesn't nag on first launch.
xattr -dr com.apple.quarantine "${DEST}" 2>/dev/null || true

# Ad-hoc re-sign so the bundle identity is stable across rebuilds
# (helps TCC/Full Disk Access grants persist).
codesign --force --deep --sign - "${DEST}" >/dev/null 2>&1 || true

# Install/refresh the login agent and load it into the user's GUI (Aqua) session — the GUI session
# is what the menu-bar NSStatusItem requires (a system domain would have no menu bar). RunAtLoad then
# starts Overture resident immediately and again at every login.
echo "==> Installing login agent: ${AGENT_DEST}"
mkdir -p "${HOME}/Library/LaunchAgents"
# Owner-only log directory for the agent's stdout/stderr (#279). launchd opens StandardOutPath at
# spawn before any app code runs, so the directory must exist now; it lives under the user's own
# Library/Logs (private, survives reboots) instead of world-readable, reboot-cleared /tmp.
AGENT_LOG_DIR="${HOME}/Library/Logs/Overture"
mkdir -p "${AGENT_LOG_DIR}"
chmod 700 "${AGENT_LOG_DIR}"
# launchd does NOT expand ~, so bake the absolute log path into the installed plist copy.
sed "s|__OVERTURE_LOG_DIR__|${AGENT_LOG_DIR}|g" "${AGENT_SRC}" > "${AGENT_DEST}"
launchctl bootstrap "${GUI_DOMAIN}" "${AGENT_DEST}" \
  || echo "    (agent bootstrap reported an error; inspect with: launchctl print ${GUI_DOMAIN}/${AGENT_LABEL})"

echo "==> Installed: ${DEST} (resident via ${AGENT_LABEL})"

if [[ "${1:-}" == "--launch" ]]; then
  # The login agent already started Overture resident. Do NOT `open` the bundle: LaunchServices may
  # not associate the agent-spawned process, so `open` launches a SECOND copy that the store lock
  # then refuses (the #282 degraded-window clash). Instead surface the running copy via its URL
  # scheme, which routes to the already-running instance.
  echo "==> Surfacing the resident Overture window"
  open "overture://show" 2>/dev/null || true
fi
