#!/usr/bin/env bash
set -euo pipefail

# Phase 1 of #1251 (Milestone 27); closes #1368. The correctness backstop that stops a STALE committed
# project.pbxproj from reaching main. Overture's Xcode project is generated by xcodegen from
# mac/project.yml, and the .pbxproj is checked in (docs/contracts.md lists it as a generated
# cross-boundary artifact). The merge scripts used to run `xcodegen generate` FIRST and then test, so a
# stale committed .pbxproj was silently regenerated in the throwaway verify worktree, passed, and the
# stale file landed on main anyway (#1368). This gate compares the committed .pbxproj against a fresh
# `xcodegen generate` and BLOCKS on any difference, run BEFORE any in-place regen so it never compares a
# file to itself.
#
# Two outcomes are kept deliberately apart (green-means-nothing-until-red): a real staleness BLOCKS with
# an actionable "regenerate and commit" message (exit 1); a xcodegen VERSION MISMATCH cannot verify
# freshness at all (a different xcodegen can emit byte-different but equivalent output, which would
# masquerade as staleness), so it emits its OWN "cannot verify" message and a distinct exit code (2),
# never a false "stale".
#
# Usage: scripts/check-pbxproj-fresh.sh [repo-or-worktree-dir]   (defaults to this repo root)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=./ci-config.sh
source "${SCRIPT_DIR}/ci-config.sh"

PBXPROJ_REL="mac/Overture.xcodeproj/project.pbxproj"

# Pure verdict over the facts the gate turns on: does the installed xcodegen match the pinned version,
# (only when it does) is the committed .pbxproj byte-identical to a fresh regen, and (only when it is not)
# did the working tree ALREADY hold that fresh regen before this check ran. Prints the operator message to
# stderr and returns a distinct code per outcome, so a fixture can drive every branch without xcodegen:
# 0 = fresh, 1 = BLOCK (stale commit, or a regen that was never committed), 2 = cannot verify (version
# mismatch or xcodegen absent).
pbxproj_freshness_verdict() {
  local installed_version="$1" pinned_version="$2" regen_matches_committed="$3" worktree_held_regen="${4:-false}"
  # Version gate first: under a different (or absent) xcodegen we cannot tell staleness from harmless
  # byte drift, so we refuse to judge and say so, rather than block on a false "stale".
  if [[ "${installed_version}" != "${pinned_version}" ]]; then
    echo "check-pbxproj-fresh: cannot verify: xcodegen version mismatch (installed '${installed_version}', pinned '${pinned_version}' in scripts/ci-config.sh)." >&2
    echo "  A different xcodegen can emit byte-different but equivalent output, which would look like staleness. Install the pinned xcodegen, or bump XCODEGEN_PINNED_VERSION in the same commit as an intended upgrade (and regenerate the project)." >&2
    return 2
  fi
  if [[ "${regen_matches_committed}" == "true" ]]; then
    return 0
  fi
  # The committed file is behind mac/project.yml either way, so both cases BLOCK (exit 1). What differs is
  # what the operator should do next. When the working tree ALREADY held the fresh regen, they have done the
  # regeneration; the problem is only that it is uncommitted, and this check restores the tree, so it has
  # just reverted their regen. Telling them to "regenerate and commit" here is the loop #1480 hit: the regen
  # they are sent to make is the one just thrown away. Name that instead of calling the file stale.
  if [[ "${worktree_held_regen}" == "true" ]]; then
    echo "check-pbxproj-fresh: BLOCK: ${PBXPROJ_REL} is regenerated but not committed. Your working tree already held the fresh 'xcodegen generate' output, so only the commit is behind mac/project.yml." >&2
    echo "  This check restores the tree after regenerating, so it has just reverted your regen and nothing is staged. Redo it in one step: (cd mac && xcodegen generate) && git add ${PBXPROJ_REL} && git commit." >&2
    return 1
  fi
  echo "check-pbxproj-fresh: BLOCK: ${PBXPROJ_REL} is stale. A fresh 'xcodegen generate' changes it, so the committed project file does not match mac/project.yml." >&2
  echo "  Regenerate and commit it before merging: cd mac && xcodegen generate, then commit ${PBXPROJ_REL}." >&2
  return 1
}

# The real gate: read the installed xcodegen version, regenerate the project in the target dir, ask git
# whether the committed .pbxproj changed, restore it so the tree is left clean, and hand the two facts to
# the pure verdict. Runs in the given dir (a throwaway verify worktree or this repo). Fails closed with
# the "cannot verify" verdict when xcodegen is not installed at all.
check_pbxproj_fresh() {
  local dir="${1:-${REPO_ROOT}}"
  local installed
  if ! command -v xcodegen >/dev/null 2>&1; then
    pbxproj_freshness_verdict "absent" "${XCODEGEN_PINNED_VERSION}" "true" "false"
    return $?
  fi
  installed="$(xcodegen --version 2>/dev/null | sed -E 's/^Version:[[:space:]]*//')"
  if [[ "${installed}" != "${XCODEGEN_PINNED_VERSION}" ]]; then
    pbxproj_freshness_verdict "${installed}" "${XCODEGEN_PINNED_VERSION}" "true" "false"
    return $?
  fi
  # Hash the working-tree file BEFORE the regen. Compared afterwards against the fresh output, this tells
  # apart a genuinely stale commit (the operator has not regenerated) from a regen the operator already made
  # but has not committed (#1480): in the latter the pre-regen file already equals the fresh output.
  local before_hash=""
  if [[ -f "${dir}/${PBXPROJ_REL}" ]]; then
    before_hash="$(git -C "${dir}" hash-object "${PBXPROJ_REL}" 2>/dev/null || true)"
  fi
  ( cd "${dir}/mac" && xcodegen generate >/dev/null )
  local regen_matches="true" worktree_held_regen="false"
  if ! git -C "${dir}" diff --quiet -- "${PBXPROJ_REL}"; then
    # A fresh regen differs from the COMMITTED file, so HEAD is behind mac/project.yml. If the working-tree
    # file we hashed before already equalled that fresh regen, the operator had regenerated; only the commit
    # is behind, and the restore below is about to undo their regen.
    regen_matches="false"
    local after_hash
    after_hash="$(git -C "${dir}" hash-object "${PBXPROJ_REL}" 2>/dev/null || true)"
    if [[ -n "${before_hash}" && "${before_hash}" == "${after_hash}" ]]; then
      worktree_held_regen="true"
    fi
  fi
  # Leave the tree as we found it: the regen above may have rewritten the committed file (and possibly
  # the schemes alongside it). Restoring the whole .xcodeproj keeps a clean tree whether fresh or stale.
  git -C "${dir}" checkout -- "mac/Overture.xcodeproj" 2>/dev/null || true
  pbxproj_freshness_verdict "${installed}" "${XCODEGEN_PINNED_VERSION}" "${regen_matches}" "${worktree_held_regen}"
}

# Allow this file to be sourced (e.g. by a test fixture) without running the gate, so
# pbxproj_freshness_verdict can be exercised directly. Mirrors merge-when-green.sh's convention.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  check_pbxproj_fresh "$@"
fi
