import Testing
import Foundation
import SwiftData

// #2692: a Downbeat booking Dan says is not happening stops holding its night.
//
// Dan, 2026-08-13: "I should have a way to remove a shoot from the days off generated by Downbeat in case
// a show gets canceled. For example, the April 20th show isn't happening but I have no way to unblock
// that." Three bookings on his live export are literally named "Potentially not happening - confirm", so
// this is a state his calendar is genuinely in, three times over.
//
// The three guards below are the ones Dan's own answer asked for, and the second is the one that fails
// without the flat-entry rule, so it is the one that was written first.
@Suite("A cancelled shoot stops holding its night (#2692)")
struct CancelledShootTests {

    private func booking(_ id: String, _ name: String, _ start: String, _ end: String? = nil)
        -> OvertureBooking {
        OvertureBooking(id: id, clientId: "c", clientDisplayName: "Client", shootName: name,
                        startDate: start, endDate: end ?? start, venueId: nil, venueName: "A room")
    }

    // The shape from Dan's live export: 2027-04-20 arrives as a named booking AND as a flat blockedDates
    // entry. Cancelling the named half must free the night, or the sheet reports success while the scout
    // still refuses it (L38: a removal has to reach every derived thing).
    @Test func cancellingTheOnlyShootFreesTheNightIncludingItsFlatEntry() {
        let bookings = [booking("b1", "April20 Show", "2027-04-20")]
        let flat = ["2027-04-20"]

        let before = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: flat, daysOff: [])
        #expect(before.conflict(performanceDate: "2027-04-20", runEndDate: nil) != nil,
                "it blocks before the cancellation, or this test proves nothing about after")

        let after = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: flat, daysOff: [],
                                          cancelledBookingIds: ["b1"])
        #expect(after.conflict(performanceDate: "2027-04-20", runEndDate: nil) == nil)
    }

    // Dan's call: the override cancels ONE shoot, never the night. On his export 2027-02-14 also holds
    // Firebird Pops Orchestra, and keying on the DATE would have freed a night he is genuinely working.
    @Test func cancellingOneOfTwoLeavesTheNightBlockedByTheOther() {
        let bookings = [booking("b1", "Feb14 Show", "2027-02-14"),
                        booking("b2", "Firebird Pops Orchestra", "2027-02-14")]

        let after = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: ["2027-02-14"],
                                          daysOff: [], cancelledBookingIds: ["b1"])
        #expect(after.conflict(performanceDate: "2027-02-14", runEndDate: nil) != nil,
                "the night is still taken, and freeing it here is the defect keying on the date would be")

        // And the sheet can say WHICH shoot is still holding it, rather than leaving the unblock looking
        // as though it did nothing.
        let still = CancelledShootEditing.stillBlocking(date: "2027-02-14", bookings: bookings,
                                                        cancelledIds: ["b1"])
        #expect(still == ["Firebird Pops Orchestra"])
    }

    @Test func cancellingBothFreesTheNight() {
        let bookings = [booking("b1", "Feb14 Show", "2027-02-14"),
                        booking("b2", "Firebird Pops Orchestra", "2027-02-14")]
        let after = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: ["2027-02-14"],
                                          daysOff: [], cancelledBookingIds: ["b1", "b2"])
        #expect(after.conflict(performanceDate: "2027-02-14", runEndDate: nil) == nil)
    }

    // The case the bare rule "suppress the flat entry when no booking remains" gets WRONG, which is why
    // the condition is "this date had a booking and none survives". A flat entry with no booking behind it
    // satisfies the bare form vacuously, and freeing it would unblock a night Downbeat blocked with
    // nothing to name it by.
    @Test func aFlatEntryWithNoBookingBehindItStillBlocks() {
        let after = BlockedCalendar.build(availability: .measured, bookings: [], exportedBlockedDates: ["2027-06-01"], daysOff: [],
                                          cancelledBookingIds: ["b1"])
        #expect(after.conflict(performanceDate: "2027-06-01", runEndDate: nil) != nil)
    }

    // A cancellation covers the booking's whole span, not only its first night.
    @Test func aMultiNightShootFreesEveryNightItHeld() {
        let bookings = [booking("b1", "Three Nighter", "2027-03-10", "2027-03-12")]
        let after = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: [], daysOff: [],
                                          cancelledBookingIds: ["b1"])
        for night in ["2027-03-10", "2027-03-11", "2027-03-12"] {
            #expect(after.conflict(performanceDate: night, runEndDate: nil) == nil, "\(night) still blocked")
        }
    }

    // Dan's own day off is HIS, and a cancelled shoot must not take it with it. The shoot landing on a day
    // off replaces it in `build`, so cancelling the shoot has to leave the day off standing.
    @Test func cancellingAShootDoesNotUnblockDansOwnDayOff() {
        let bookings = [booking("b1", "A Shoot", "2027-07-04")]
        let daysOff = [DayOffRange(startDate: "2027-07-04", endDate: "2027-07-04", note: "Holiday")]
        let after = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: [], daysOff: daysOff,
                                          cancelledBookingIds: ["b1"])
        let day = after.conflict(performanceDate: "2027-07-04", runEndDate: nil)
        #expect(day?.kind == .dayOff)
        #expect(day?.name == "Holiday")
    }

    // A cancellation survives a fresh export that still carries the booking, which is the whole reason it
    // is a stored override rather than a deletion: `build` re-reads the export on every call (L116).
    @Test func aCancellationSurvivesAnExportThatStillCarriesTheBooking() {
        let bookings = [booking("b1", "April20 Show", "2027-04-20")]
        // Two separate builds standing for two separate exports, both carrying the booking.
        for _ in 0..<2 {
            let cal = BlockedCalendar.build(availability: .measured, bookings: bookings, exportedBlockedDates: ["2027-04-20"],
                                            daysOff: [], cancelledBookingIds: ["b1"])
            #expect(cal.conflict(performanceDate: "2027-04-20", runEndDate: nil) == nil)
        }
    }

    // Which booking a sheet row is about. The row draws a `Day`, which carries a date and a name and
    // deliberately not a booking id, because `Day.key` is what a prospect stores as its conflict and
    // widening it would re-key every flagged card on the live store.
    @Test func aRowResolvesToTheBookingsBehindIt() {
        let bookings = [booking("b1", "Feb14 Show", "2027-02-14"),
                        booking("b2", "Firebird Pops Orchestra", "2027-02-14")]
        let day = BlockedCalendar.Day(date: "2027-02-14", kind: .bookedShoot, name: "Feb14 Show")
        #expect(CancelledShootEditing.bookingIds(for: day, in: bookings) == ["b1"],
                "and NOT the other shoot on the same night, which is the whole of Dan's call")
    }

    // Two bookings alike in NAME and date are one row by construction (`build` collapses them), so the row
    // cancels both. Stated rather than discovered: they are indistinguishable to Dan on screen.
    @Test func aRowStandingForTwoIdenticalBookingsCancelsBoth() {
        let bookings = [booking("b1", "Same Name", "2027-02-14"),
                        booking("b2", "Same Name", "2027-02-14")]
        let day = BlockedCalendar.Day(date: "2027-02-14", kind: .bookedShoot, name: "Same Name")
        #expect(CancelledShootEditing.bookingIds(for: day, in: bookings) == ["b1", "b2"])
    }

    // The flat entry's row has no booking behind it, so it offers nothing to cancel rather than guessing
    // at the date. A control beside a rule that cannot act on it is a false affordance (L109).
    @Test func aFlatEntryRowHasNothingToCancel() {
        let day = BlockedCalendar.Day(date: "2027-04-20", kind: .bookedShoot, name: nil)
        #expect(CancelledShootEditing.bookingIds(for: day, in: [booking("b1", "X", "2027-04-20")]).isEmpty)
    }

    // A day off row is not a shoot, and must never resolve to one.
    @Test func aDayOffRowIsNotAShoot() {
        let day = BlockedCalendar.Day(date: "2027-04-20", kind: .dayOff, name: "Holiday")
        #expect(CancelledShootEditing.bookingIds(for: day, in: [booking("b1", "Holiday", "2027-04-20")])
                    .isEmpty)
    }
}

// The store half, kept apart because it needs a container.
@MainActor
@Suite("Cancelling and restoring a shoot in the store (#2692)")
struct CancelledShootStoreTests {

    private func context() throws -> ModelContext {
        let container = try ModelContainer(
            for: Schema(AppSchema.models),
            configurations: ModelConfiguration(isStoredInMemoryOnly: true))
        return ModelContext(container)
    }

    private func booking(_ id: String, _ name: String, _ start: String) -> OvertureBooking {
        OvertureBooking(id: id, clientId: "c", clientDisplayName: "Client", shootName: name,
                        startDate: start, endDate: start, venueId: nil, venueName: "A room")
    }

    @Test func cancellingThenRestoringPutsTheNightBack() throws {
        let ctx = try context()
        let empty: DayOffEditing.Export = ([], [], .ok)

        #expect(CancelledShootEditing.cancel(bookingIds: ["b1"], named: "April20 Show",
                                             on: "2027-04-20", export: empty, in: ctx) == 1)
        #expect(CancelledShootEditing.cancelledIds(in: ctx) == ["b1"])

        #expect(CancelledShootEditing.restore(bookingIds: ["b1"], export: empty, in: ctx) == 1)
        #expect(CancelledShootEditing.cancelledIds(in: ctx).isEmpty)
    }

    // Pressing it twice is one cancellation, not two rows that could disagree.
    @Test func cancellingTheSameShootTwiceAddsNothingTheSecondTime() throws {
        let ctx = try context()
        let empty: DayOffEditing.Export = ([], [], .ok)
        #expect(CancelledShootEditing.cancel(bookingIds: ["b1"], named: "X", on: "2027-04-20",
                                             export: empty, in: ctx) == 1)
        #expect(CancelledShootEditing.cancel(bookingIds: ["b1"], named: "X", on: "2027-04-20",
                                             export: empty, in: ctx) == 0)
        #expect(CancelledShootEditing.rows(in: ctx).count == 1)
    }

    // The sweep is hygiene: it clears a row whose booking the export no longer carries.
    @Test func theSweepClearsARowDownbeatHasDropped() throws {
        let ctx = try context()
        let empty: DayOffEditing.Export = ([], [], .ok)
        CancelledShootEditing.cancel(bookingIds: ["gone", "still-there"], named: "X", on: "2027-04-20",
                                     export: empty, in: ctx)

        #expect(CancelledShootEditing.sweep(against: [booking("still-there", "X", "2027-04-20")],
                                            in: ctx) == 1)
        #expect(CancelledShootEditing.cancelledIds(in: ctx) == ["still-there"])
    }

    // The direction that would be catastrophic, and the reason the sweep refuses an empty list. An export
    // that failed to load yields NO bookings, and reading that as "Downbeat dropped every booking" would
    // delete every cancellation Dan has made, all at once. An absent source and an empty one are different
    // situations (L214).
    @Test func theSweepRefusesAnEmptyExportRatherThanClearingEverything() throws {
        let ctx = try context()
        let empty: DayOffEditing.Export = ([], [], .ok)
        CancelledShootEditing.cancel(bookingIds: ["b1", "b2"], named: "X", on: "2027-04-20",
                                     export: empty, in: ctx)
        #expect(CancelledShootEditing.sweep(against: [], in: ctx) == 0)
        #expect(CancelledShootEditing.cancelledIds(in: ctx).count == 2)
    }
}
