import Testing
import Foundation

// #3420: what the OmniFocus reads COST, and whether anything can say so.
//
// The freeze in #3419 was sampled inside `completedOvertureTasks()`. That read walks every reminder
// Overture has ever created and Dan has ever ticked off, with no horizon and no pruning, so the
// population only grows; and it paid one Apple event per task, because `note of t` inside a repeat
// over a `whose` result is a remote property read per turn of the loop. Linear in an ever growing
// set, in round trips.
//
// Two things are asserted here. That the notes are fetched in ONE plural read, so the loop that
// follows is over local strings and costs nothing. And that the pass RECORDS what it walked: before
// this, a read that took four minutes and a read that took forty milliseconds left exactly the same
// trace, which is none (L98).
@Suite("OmniFocus read cost (#3420)")
struct OmniFocusReadCostTests {
    // The script is generated by a pure function precisely so this can be asserted: the AppleScript
    // boundary itself can have no test, which is why the client's other decisions are static too.
    @Test func theNotesAreFetchedInOnePluralReadRatherThanOnePerTask() {
        let src = AppleScriptOmniFocusClient.overtureTasksScript(completed: true)
        #expect(src.contains("note of (every task of ovt whose completed is true)"))
    }

    // The property that actually bounds the cost, stated as itself rather than as the spelling above:
    // nothing inside the loop may reach back into OmniFocus. A guard on the fetch line alone would
    // pass a script that fetched the notes in one go and then read a second property per task.
    @Test func theLoopBodyMakesNoFurtherRequestOfOmniFocus() {
        let src = AppleScriptOmniFocusClient.overtureTasksScript(completed: true)
        let body = src.components(separatedBy: "repeat with").dropFirst().joined()
        let loop = body.components(separatedBy: "end repeat").first ?? ""
        #expect(!loop.isEmpty, "the script must still have a loop for this to be measuring anything")
        // `of t` is how a remote read is spelled here: `note of t`, `id of t`, `name of t`.
        #expect(!loop.contains(" of t\n"))
        #expect(!loop.contains(" of t "))
    }

    // Both reads share the generator, so the incomplete one cannot quietly keep the per-task shape
    // after the completed one is fixed (L30: the class, not the instance).
    @Test func bothReadsAreBuiltByTheSameGenerator() {
        let open = AppleScriptOmniFocusClient.overtureTasksScript(completed: false)
        let done = AppleScriptOmniFocusClient.overtureTasksScript(completed: true)
        #expect(open.contains("note of (every task of ovt whose completed is false)"))
        #expect(open.replacingOccurrences(of: "completed is false", with: "completed is true") == done)
    }

    private final class CountingClient: OmniFocusClient, @unchecked Sendable {
        let completedTasks: [OmniFocusSync.ExistingTask]
        init(completed: [OmniFocusSync.ExistingTask]) { completedTasks = completed }
        func existingOvertureTasks() throws -> [OmniFocusSync.ExistingTask] { [] }
        func completedOvertureTasks() throws -> [OmniFocusSync.ExistingTask] { completedTasks }
        func create(_ task: OmniFocusSync.DesiredTask) throws {}
        func complete(_ task: OmniFocusSync.ExistingTask) throws {}
    }

    private final class UnreadableClient: OmniFocusClient, @unchecked Sendable {
        struct Refused: Error {}
        func existingOvertureTasks() throws -> [OmniFocusSync.ExistingTask] { [] }
        func completedOvertureTasks() throws -> [OmniFocusSync.ExistingTask] { throw Refused() }
        func create(_ task: OmniFocusSync.DesiredTask) throws {}
        func complete(_ task: OmniFocusSync.ExistingTask) throws {}
    }

    private final class SilentNotifier: OmniFocusNotifier {
        func notifyPermissionNeeded() {}
        func notifySyncFailed(_ message: String) {}
    }

    private func task(_ key: String) -> OmniFocusSync.ExistingTask {
        OmniFocusSync.ExistingTask(naturalKey: key, recipientId: "a@example.invalid",
                                   dueDate: Date(timeIntervalSince1970: 1_780_000_000))
    }

    private func freshDefaults() throws -> UserDefaults {
        try #require(UserDefaults(suiteName: "of-readcost-\(UUID().uuidString)"))
    }

    // The clock is injected rather than read, so this asserts the duration REPORTED and not what else
    // the machine was doing while it ran (L224, L290, L524).
    @Test func theRunSaysHowManyCompletedTasksItWalkedAndHowLongTheyTook() throws {
        var ticks = [0.0, 2.5].makeIterator()
        let result = try OmniFocusSync.apply(
            desired: [], client: CountingClient(completed: [task("a|2026-10-25|x"), task("b|2026-10-25|x")]),
            now: { Date(timeIntervalSince1970: 1_780_000_000 + (ticks.next() ?? 99)) })
        #expect(result.completedRead.tasks == 2)
        #expect(result.completedRead.seconds == 2.5)
    }

    // Driven through the RUNNER, which is what actually stores it. Asserting against `apply` alone
    // would be a test satisfied by a fixture in which the write could not happen at all (L159).
    @Test @MainActor func aCompletedSyncStoresWhatItsReadWalked() async throws {
        let d = try freshDefaults()
        _ = await OmniFocusSyncRunner.run(desired: [], permission: .granted,
                                          client: CountingClient(completed: [task("a|2026-10-25|x")]),
                                          notifier: SilentNotifier(), now: Date(), defaults: d,
                                          worker: BlockingWorkThread(name: "test-readcost-ok"))
        #expect(d.bool(forKey: OmniFocusSyncStatus.completedReadTakenKey))
        #expect(d.integer(forKey: OmniFocusSyncStatus.completedReadTasksKey) == 1)
    }

    // A read that FAILED walked nothing, and zero is a real measurement: recording it would make the
    // emptiest possible failure the fastest possible read (L98, L11).
    @Test @MainActor func aReadThatFailedRecordsNoShapeAtAll() async throws {
        let d = try freshDefaults()
        _ = await OmniFocusSyncRunner.run(desired: [], permission: .granted, client: UnreadableClient(),
                                          notifier: SilentNotifier(), now: Date(), defaults: d,
                                          worker: BlockingWorkThread(name: "test-readcost-refused"))
        #expect(d.bool(forKey: OmniFocusSyncStatus.completedReadTakenKey) == false)
        // The positive control: the run genuinely happened and genuinely failed, so the absence above
        // is about the read and not about nothing having run (L159, L171).
        #expect(OmniFocusSyncStatus.lastFailure(from: d) != nil)
    }

    // The measurement #3420 asks for has to be somewhere a person can read it, or it is a number the
    // code holds and nobody ever sees (L357).
    @Test func theShapeHasASentenceAndTheNeverMeasuredCaseIsItsOwn() {
        let measured = OmniFocusSyncStatus.completedReadLine(taken: true, tasks: 812, seconds: 41.25)
        #expect(measured.contains("812"))
        let never = OmniFocusSyncStatus.completedReadLine(taken: false, tasks: 0, seconds: 0)
        #expect(never != measured)
        #expect(!never.isEmpty)
        // Zero read is not "never measured": a fresh install has ticked nothing off yet, and both
        // sentences would otherwise be the same claim about two different facts (L11).
        #expect(OmniFocusSyncStatus.completedReadLine(taken: true, tasks: 0, seconds: 0.2) != never)
    }
}
