import Foundation
import SwiftData

// #2692: a Downbeat booking Dan has told Overture is not happening, so it stops keeping the night clear.
//
// Dan, 2026-08-13: "I should have a way to remove a shoot from the days off generated by Downbeat in case
// a show gets canceled. For example, the April 20th show isn't happening but I have no way to unblock
// that." His export really is in that state: three bookings are literally named "Potentially not
// happening - confirm", which is a booking he is not ready to cancel in Downbeat and does not want
// Overture protecting.
//
// A STORED OVERRIDE that `BlockedCalendar.build` applies, never a deletion. `build` re-reads `bookings`
// and `blockedDates` from the export on every call, so anything deleted locally comes back with the next
// export. A cancellation is a preference, and a preference is enforced by filtering what is shown, never
// by deleting the data behind it (L116), which is also what lets Dan put it back.
//
// Keyed on the BOOKING, never the date (Dan's call, 2026-08-18). Keying on the date would have freed
// 2027-02-14 (which also holds Firebird Pops Orchestra) and 2027-05-30 (Sorenson and DiOrio, plus God
// Lives in Glass) on his live export, so the scout would have started offering shows for nights he is
// genuinely booked on. Cancelling a named shoot removes that shoot and nothing else.
//
// That key is also what makes a stale row harmless, which is why there is no expiry rule here. A booking
// id is Downbeat's own, so a FUTURE booking landing on the same date carries a different one and is never
// suppressed by an override left behind. `CancelledShootSweep` clears the rows whose booking the export
// no longer carries, as hygiene rather than as a correctness guard.
@Model
final class CancelledShoot {
    // Not `id`: PersistentModel already refines Identifiable through persistentModelID. Unique at the
    // STORE layer, on `PromotedProducer`'s precedent, so two presses racing on one shoot cannot leave two
    // rows that disagree.
    @Attribute(.unique) var bookingId: String
    // What the shoot was called and when it ran, copied at the moment of cancelling. Kept so the sheet can
    // say WHICH shoot Dan waved through even after Downbeat stops exporting it, and so the sweep below has
    // something readable to name. Never read as the current truth about the booking: the export is that.
    var shootName: String
    var startDate: String
    var cancelledAt: Date

    init(bookingId: String, shootName: String, startDate: String, cancelledAt: Date = Date()) {
        self.bookingId = bookingId
        self.shootName = shootName
        self.startDate = startDate
        self.cancelledAt = cancelledAt
    }
}
